# Generated by Django 3.2.7 on 2021-09-10 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_alter_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(code='nomatch', message='Znak liczba liczba Znak', regex='\\D\\d\\d\\D')]),
        ),
    ]
