# Generated by Django 3.2.7 on 2021-09-10 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0005_auto_20210910_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(code='nomatch', message='Correct format is XXX-XX-XXXXX-XX-X, where X is a number from 0 to 9', regex='\\d\\d\\d-\\d\\d-\\d\\d\\d\\d\\d-\\d\\d-\\d')]),
        ),
    ]
